In [41]:
import tensorflow as tf

# with tf.variable_scope("greg", reuse=True) as scope:
#Source code with the blog post at http://monik.in/a-noobs-guide-to-implementing-rnn-lstm-using-tensorflow/
import numpy as np
import random
from random import shuffle
import tensorflow as tf

# from tensorflow.models.rnn import rnn_cell
# from tensorflow.models.rnn import rnn

NUM_EXAMPLES = 1000

# train_input = ['{0:020b}'.format(i) for i in range(2**10)]
# shuffle(train_input)
# train_input = [map(int,i) for i in train_input]
# ti  = []
# for i in train_input:
#     temp_list = []
#     for j in i:
#             temp_list.append([j])
#     ti.append(np.array(temp_list))
# train_input = ti

# train_output = []
# for i in train_input:
#     count = 0
#     for j in i:
#         if j[0] == 1:
#             count+=1
#     temp_list = ([0]*21)
#     temp_list[count]=1
#     train_output.append(temp_list)

# test_input = train_input[NUM_EXAMPLES:]  # 24,20
# test_output = train_output[NUM_EXAMPLES:] # 24,21 
# train_input = train_input[:NUM_EXAMPLES] # 1000,20
# train_output = train_output[:NUM_EXAMPLES] # 1000,21

def get_batch():
    batch = [[]]
    total = 0
    for i in range(0,11):
        x = random.randint(1,10)
        batch[0].append([x])
        total += x
    return np.array(batch), [total*.1]

greg = get_batch()

print(greg)


print('train data loaded')

(array([[[ 3],
        [ 1],
        [ 9],
        [ 5],
        [ 2],
        [ 9],
        [ 5],
        [10],
        [ 1],
        [ 6],
        [ 6]]]), [5.7])
train data loaded


In [ ]:
with tf.variable_scope("greg", reuse=True) as scope:

    data = tf.placeholder(tf.float32, [None, 11,1]) #Number of examples, number of input, dimension of each input
    target = tf.placeholder(tf.float32, [1])
    num_hidden = 11
    cell = tf.nn.rnn_cell.LSTMCell(num_hidden, state_is_tuple=True)
    val, _ = tf.nn.dynamic_rnn(cell, data, dtype=tf.float32)
    
#     val = tf.transpose(val, [1, 0, 2])
#     last = tf.gather(val, int(val.get_shape()[0]) - 1)
    last = val[0,10,:]
    lastTotal = tf.reduce_sum(tf.abs(last))
    loss = tf.abs(target[0]-lastTotal)
#     optimizer = tf.train.AdagradOptimizer(.03)
#     optimizer = tf.train.AdamOptimizer(1e-2)
    optimizer = tf.train.GradientDescentOptimizer(.03)
    
    train_step = optimizer.minimize(loss)

#     weight = tf.Variable(tf.truncated_normal([num_hidden, int(target.get_shape()[1])]))
#     bias = tf.Variable(tf.constant(0.1, shape=[target.get_shape()[1]]))
#     prediction = tf.nn.softmax(tf.matmul(last, weight) + bias)
#     cross_entropy = -tf.reduce_sum(target * tf.log(prediction))
#     optimizer = tf.train.AdamOptimizer()
#     minimize = optimizer.minimize(cross_entropy)
#     mistakes = tf.not_equal(tf.argmax(target, 1), tf.argmax(prediction, 1))
#     error = tf.reduce_mean(tf.cast(mistakes, tf.float32))
    
    init_op = tf.initialize_all_variables()
    sess = tf.Session()
    sess.run(init_op)

#     inp, out = train_input[0:1], train_output[0:1]
    
#     print(inp)
    
    for i in range(0,15001):
        inp = get_batch()
        sess.run(train_step,{data:inp[0],target:inp[1]})
        if(i%200 ==0):
            print(str(i)+': '+str(sess.run(loss,{data:inp[0],target:inp[1]})))
    

0: 1.20132
200: 0.195185
400: 1.63602
600: 0.529652
800: 0.0677576
1000: 0.0672946
1200: 0.607251
1400: 1.10967
1600: 1.18671
1800: 0.926635
2000: 0.747303
2200: 0.288234
2400: 0.892438
2600: 0.0340867
2800: 0.0112767
3000: 0.0523024
3200: 0.47391
3400: 0.303184
3600: 0.113762
3800: 0.676772
4000: 0.202333
4200: 0.151063
4400: 0.210973
4600: 0.0549126
4800: 0.150285
5000: 0.00504875
5200: 0.365706
5400: 0.369738
5600: 0.466591
5800: 0.25811
6000: 0.156282
6200: 0.177514
6400: 0.524967
6600: 0.370193
6800: 0.463995
7000: 0.117648
7200: 0.177372
7400: 0.0108557
7600: 0.443592
7800: 0.403214
8000: 0.0800943
8200: 0.59173
8400: 0.0811105
8600: 0.0537829
8800: 0.224004
9000: 0.194407
9200: 0.109201
9400: 0.0976195
9600: 0.0731497
9800: 0.0065403
10000: 0.698755
10200: 0.173537
10400: 0.0516372
10600: 0.20481
10800: 0.210446
11000: 0.278581
11200: 0.232893
11400: 0.0240502
11600: 0.132368
11800: 0.0928464
12000: 0.285971


In [5]:
init_op = tf.initialize_all_variables()
sess = tf.Session()
sess.run(init_op)

inp, out = train_input[0:1], train_output[0:1]
print(sess.run(val,{data: inp, target: out}))

# batch_size = 100
# no_of_batches = int(len(train_input) / batch_size)
# print(no_of_batches)
# epoch = 50
# for i in range(epoch):
#     ptr = 0
#     for j in range(no_of_batches):
#         inp, out = train_input[ptr:ptr+batch_size], train_output[ptr:ptr+batch_size]
#         ptr+=batch_size
#         sess.run(minimize,{data: inp, target: out})
#     print ("Epoch "+str(i))
# incorrect = sess.run(error,{data: test_input, target: test_output})
# print(sess.run(prediction,{data: [[[1],[0],[0],[1],[1],[0],[1],[1],[1],[0],[1],[0],[0],[1],[1],[0],[1],[1],[1],[0]]]}))
# print('Epoch {:2d} error {:3.1f}%'.format(i + 1, 100 * incorrect))
# sess.close()

[[[ 0.          0.          0.          0.        ]]

 [[ 0.          0.          0.          0.        ]]

 [[ 0.          0.          0.          0.        ]]

 [[ 0.          0.          0.          0.        ]]

 [[ 0.          0.          0.          0.        ]]

 [[ 0.          0.          0.          0.        ]]

 [[ 0.          0.          0.          0.        ]]

 [[ 0.          0.          0.          0.        ]]

 [[ 0.          0.          0.          0.        ]]

 [[ 0.          0.          0.          0.        ]]

 [[-0.10094541  0.01640086 -0.14926097  0.08908965]]

 [[-0.17274372  0.01264222 -0.19872776  0.16348584]]

 [[-0.17223734 -0.01183535 -0.1075826   0.19914645]]

 [[-0.18111679 -0.00191544 -0.1540789   0.20453331]]

 [[-0.18668649 -0.01704033 -0.07527536  0.23238693]]

 [[-0.12974223 -0.02258761 -0.01482019  0.20044228]]

 [[-0.08711073 -0.01824811  0.01834305  0.16460145]]

 [[-0.0563496  -0.00907683  0.03430592  0.13233964]]

 [[-0.1238291   0.01831533 -